"""An expansie dictionary that contains a full registry of planets (both established fiction)
   and original that containskey value pairs consisting of the planet name and a conversion
   factor for converting an individual's age on that plnaet to earth years (via multiplication)
"""

# Note - Data Generated by Gemini

Planets_Rot = {
    # === ANIME / SPECIFIC REQUESTS ===
    "Namek": 0.61,              # Dragon Ball Z (Shorter year, age faster)
    "Oniboshi": 1.95,           # Urusei Yatsura (Longer year, age slower)
    "Tamaran": 1.15,            # DC / Teen Titans (Slightly slower aging)
    "Chakra Nexus Prime": 0.05, # Otsutsuki Clan Home (Ancient, slow cycles)
    "Jurai": 0.01,              # Tenchi Muyo (Extremely slow cycle / magical time)
    "Planet Vegeta": 0.90,       # Dragon Ball Z (Slightly faster aging)
    "Ygam (The Citadel)": 1.05, # Rick and Morty
    "Planet Bob": 1.30,         # Futurama
    "Omicron Persei 8": 2.10,   # Futurama
    "Tralfa": 0.75,             # Hitchhiker's Guide
    "Planet Shiveria": 1.50,    # Kirby
    "Planet Popstar": 0.98,     # Kirby
    "Planet Gunsmoke": 1.45,    # Trigun
    "Remina (Planet Eater)": 0.0001, # Junji Ito
    "Cybertron": 4.00,          # Transformers
    "Iscandar": 0.85,           # Space Battleship Yamato
    "Gamilas": 1.20,            # Space Battleship Yamato
    "Planet Cleo": 1.10,        # Astro Boy
    "Aria": 0.70,               # Aria the Animation (Terraformed Mars)
    "Planet Wahn": 1.60,        # Space Dandy
    "Planet P": 0.95,           # Space Dandy
    "Midwich": 1.35,            # NGE
    "Lagrange Point": 1.00,     # Gundam/Macross
    "Side 3 (Gundam)": 1.00,    # Gundam
    "Side 7 (Gundam)": 1.00,    # Gundam
    "Planet Latia": 0.80,       # Cyborg 009
    "Planet Ro": 1.25,          # Galaxy Express 999
    "Planet Crolon": 1.70,      # Space Pirate Captain Harlock
    "Neo-Venezia": 0.70,        # Aria the Animation
    "Arboreal": 0.65,           # Knights of Sidonia
    "K-T (Gundam IBO)": 1.55,   # Gundam IBO
    "Planet Aquamarine": 0.97,  # Sailor Moon
    "Alshain": 1.17,            # Legend of the Galactic Heroes
    "Geiersburg": 1.00,         # Legend of the Galactic Heroes
    "Ares (Cowboy Bebop)": 1.88, # Martian orbit cycle
    "Venus (Cowboy Bebop)": 0.61, # Closer orbit to the sun
    "Jupiter Station": 1.00,    # Cowboy Bebop
    "Neo-Kyoto": 1.00,          # Gundam G
    "Space Colony Kaguya": 1.00, # Space Dandy
    "Gunbuster Home": 0.02,     # Gunbuster (Relativistic effects)
    "Yucatan": 1.33,            # Cowboy Bebop
    "Zenkai": 0.83,             # DBZ
    "Planet X (Bender's Home)": 1.50, # Futurama
    "Planet of the Apes": 1.00, # Planet of the Apes
    "Tralfamadore": 0.50,       # Slaughterhouse-Five
    "Klendagon": 1.20,          # Mass Effect
    "Palaven": 0.90,            # Mass Effect
    "Rannoch": 1.00,            # Mass Effect
    "Haestrom": 0.80,           # Mass Effect

    # === NEW ANIME & FANTASY WORLDS (30 Additional) ===
    # --- Sailor Moon & Senshi Home Bases (Fictionalized) ---
    "Cydonia (Mars Colony)": 1.88,      # Based on Mars' year
    "Cloud Sea (Jupiter)": 0.50,        # Fast orbital mechanics
    "Sulfur Venus": 0.61,               # Based on Venus' year
    "Moon Kingdom (Pre-Terra)": 0.40,   # Shorter lunar cycle
    "Uranus Orbital Base": 3.00,        # Very long orbital path
    "Neptune Hydro-Station": 5.00,      # Extremely long orbital path
    "Pluto Temporal Gate": 0.10,        # Time-related anomaly
    "Saturn Veil": 4.50,                # Long orbital cycle
    
    # --- Urusei Yatsura & Related Worlds ---
    "Piton Star (Benten)": 1.20,        # Princess Clara's (Benten's) home star
    "Tigris Major (Lum Home)": 0.95,    # Lum's home (Slightly faster rotation)
    "Space-Time Distortion Zone": 0.005, # For characters like Ten
    "Nebula 77 (Dimensional)": 1.50,
    
    # --- Space Opera / Mecha / Fantasy Anime ---
    "Gaia (Escaflowne)": 1.10,          # Fantasy world with different time flow
    "Planet Chem (Outlaw Star)": 1.50,   # Slower rotation/orbit
    "Heavens Gate (Gundam)": 1.00,      # Synchronized orbital colony
    "Valkyrie Base (Macross)": 0.90,    # Faster rotational period
    "Planet Frolat (Cowboy Bebop)": 1.30,
    "The Great Labyrinth (Anime)": 3.50, # Extremely long cycles
    "Arcadia Bridge": 0.85,             # Space Pirate Harlock related
    "Andromeda Xenos": 2.15,
    "Celestial Haven": 0.88,
    
    # --- Generic Sci-Fi/Fictional Additions ---
    "Whispering Woods IV": 1.65,
    "Starfall Citadel": 0.75,
    "Crimson Orbit": 1.25,
    "Neon Abyss": 2.10,
    "Aura Nebula": 0.55,
    "Echo Star Gamma": 1.11,
    "Solaris Nova": 0.99,
    "Chronos Echo": 0.35,
    "Kagura System": 1.05,
    "Phantom Moon": 1.70,
    
    # === STAR WARS (Estimated Conversion Factor) ===
    "Tatooine": 1.2,
    "Alderaan": 1.0,
    "Coruscant": 1.0,
    "Hoth": 1.7,
    "Kashyyyk": 0.85,
    "Naboo": 1.1,
    "Mustafar": 2.5,
    "Endor": 0.95,
    "Bespin": 3.0,
    "Yavin 4": 1.3,
    "Kamino": 0.7,
    "Mandalore": 1.5,
    "Geonosis": 1.8,
    "Exegol": 4.1,
    "Jedha": 1.05,
    "Ahch-To": 0.5,
    "Dathomir": 2.2,
    "Canto Bight": 1.1,
    "Crait": 1.9,
    "Ajan Kloss": 0.9,

    # === STAR TREK (Estimated Conversion Factor) ===
    "Vulcan": 0.75,
    "Romulus": 1.25,
    "Qo'noS (Klingon Home)": 0.95,
    "Andoria": 1.4,
    "Tellar Prime": 1.0,
    "Bajor": 1.05,
    "Cardassia Prime": 0.88,
    "Trill": 1.1,
    "Ferenginar": 1.6,
    "Risa": 0.98,
    "Talos IV": 0.5,
    "Orion": 1.3,
    "Borg Cube 127": 1.0, # Time dilation negligible
    "Deep Space Nine": 1.0,
    "Axanar": 0.8,
    "Xindus": 1.7,
    "I'Kala": 1.2,
    "Gornar": 2.1,
    "Denobula": 1.05,
    "Babel": 1.1,
    
    # === MARVEL / DC (Estimated Conversion Factor) ===
    "Asgard": 0.1,
    "Xandar": 0.85,
    "Sakaar": 1.4,
    "Ego (The Living Planet)": 0.001,
    "Krypton": 1.0,
    "Oa": 0.08,
    "Rann": 1.2,
    "Thanagar": 0.9,
    "Apokolips": 1.8,
    "New Genesis": 0.5,
    "Hala (Kree Home)": 1.3,
    "Skrullos": 1.1,
    "Knowhere": 1.0,
    "Titan (Saturn Moon)": 1.7,
    "Contraxia": 0.7,
    "Vormir": 1.0,
    "Wundagore": 1.2,
    "Aerie (Aquitania)": 0.9,
    "Shi'ar Home World": 1.05,
    "Daxam": 0.8,

    # === DUNE / MISC SCI-FI (Estimated Conversion Factor) ===
    "Arrakis": 1.5,
    "Caladan": 0.9,
    "Giedi Prime": 1.1,
    "Kaitain": 1.0,
    "Salusa Secundus": 1.4,
    "LV-426 (Acheron)": 1.8,
    "Fury 161": 2.0,
    "Caprica": 1.0,
    "Gemenon": 1.05,
    "Picon": 0.95,
    "Aerilon": 1.1,
    "Taurus (Serenity)": 1.05,
    "Persephone": 1.2,
    "Bellerophon": 0.8,
    "Miranda": 1.3,
    "Magrathea": 0.5,
    "Vogsphere": 2.5,
    "Barrayar": 1.1,
    "Komarr": 1.05,
    "Midworld": 0.8,

    # === GAMING / FANTASY (Estimated Conversion Factor) ===
    "Reach (Halo)": 1.0,
    "Eos (Mass Effect)": 0.9,
    "Tuchanka (Mass Effect)": 1.5,
    "Thessia (Mass Effect)": 0.7,
    "Sur'Kesh (Mass Effect)": 1.2,
    "Cybertron": 4.0,
    "Helghan (Killzone)": 1.9,
    "Pandora (Borderlands)": 1.6,
    "Aetherius (Skyrim)": 0.01,
    "Gallifrey": 0.005,
    "Skaro": 1.8,
    "Mondas": 2.1,
    "Planet Zebes": 1.3,
    "Tallon IV": 0.9,
    "Dantooine": 1.05,
    "Manaan": 1.2,
    "Korriban": 1.4,
    "Tython": 0.8,
    "Hutta": 2.3,
    "Dromund Kaas": 1.1,

    # === NEAR FUTURE / COLONIES (Estimated Conversion Factor) ===
    "Mars Colony-I": 1.88, # Martian year length
    "Jupiter Station Io": 1.0,
    "Luna Colony (Moon)": 1.0,
    "Ceres Station": 1.05,
    "Ganymede Habitat": 1.1,
    "Titan Research Base": 1.6,
    "Proxima b Colony": 0.3,
    "Kepler-22b": 0.8,
    "Gliese 581 g": 0.9,
    "New Earth (Terra Nova)": 1.02,
    "Colony 7": 1.0,
    "The Belt (Asteroid)": 1.0,
    "New Sydney": 1.15,
    "K-9 (Mining)": 1.7,
    "Nova Prime": 0.98,
    "Ares VI": 1.8,
    "Hope VI": 1.05,
    "Epsilon Eridani b": 1.4,
    "TRAPPIST-1e": 0.7,
    "Zeta Reticuli II": 1.2,

    # === ADDITIONAL FICTIONAL WORLDS (To reach ~200) ===
    "Chrono Trigger World": 1.0,
    "Planet Gleep": 2.5,
    "Xylos Minor": 1.5,
    "Tralfa": 1.1,
    "Soylent Green VI": 0.9,
    "Solaris": 0.6,
    "Terminus": 1.0,
    "Trantor": 1.0,
    "Zardos Prime": 3.1,
    "Planet X (Bender's Home)": 1.5,
    "Dune II": 1.4,
    "Kryten's World": 1.0,
    "Planet B-12": 0.7,
    "Aethelgard": 1.05,
    "Gormenghast": 1.2,
    "Midian": 1.3,
    "Acheron V": 1.8,
    "Zork": 1.0,
    "Kylos": 0.9,
    "Veridia Prime": 1.1,
    "Seraphim": 0.85,
    "Grimore": 1.25,
    "Ragnarok": 0.75,
    "Nirn": 1.0,
    "Morrowind": 1.1,
    "Auriga": 1.3,
    "Primeval Earth": 0.5,
    "Altair IV": 1.6,
    "Argus X": 1.4,
    "Rigel VII": 1.7,
    "Cygnus X-1": 0.4,
    "Stygia": 2.1,
    "Atlantis (Ancient)": 0.8,
    "Elysium (Ring)": 1.0,
    "Hades (Pluto)": 3.5,
    "Phobos Station": 1.0,
    "Deimos Base": 1.0,
    "Gliese 667 Cc": 0.7,
    "HD 40307 g": 1.1,
    "Gliese 581 c": 0.9,
    "Kepler-186f": 1.2,
    "Ygam (The Citadel)": 1.0,
    "Xylos IX": 1.3,
    "Solis III": 1.05,
    "Giga": 0.8,
    "Terra Alpha": 1.1,
    "Ryloth": 1.2,
    "Zabrak": 1.3,
    "Rodian": 1.4,
    "Zygerria": 1.5,
    "Iridonia": 1.6,
    "Umbra": 1.7,
    "Felucia": 1.8,
    "Mugato": 1.9,
    "Rigel X": 2.0,
    "Planet of the Apes": 1.0,
    "Tralfamadore": 0.5,
    "Klendagon": 1.2,
    "Palaven": 0.9,
    "Rannoch": 1.0,
    "Haestrom": 0.8,
    "Aite": 1.1,
    "Hesperus": 1.3,
    "Prometheus IX": 1.5,
    "Tarkus": 1.7,
    "Orionis": 1.9,
    "Nebulon": 2.1,
    "Grimoire II": 2.3,
    "Tundra VI": 2.5,
    "Oasis Beta": 2.7,
    "Ironclad V": 2.9,
    "Alpha Centauri Bb": 0.6,
    "Tau Ceti f": 0.7,
    "Ross 128 b": 0.4,
    "Luyten b": 0.5,
    "Wolf 1061 c": 0.8,
    "Gliese 667 Cg": 0.9,
    "55 Cancri e": 0.3,
    "HD 209458 b": 0.55,
    "WASP-17b": 0.75,
    "HAT-P-7b": 0.95,
    "Kepler-10b": 1.15,
    "Corot-7b": 1.35,
    "Gliese 581 d": 1.55,
    "HD 85512 b": 1.75,
    "Alpha Centauri B": 1.95,
    "Sirius B": 2.15,
    "Vega": 2.35,
    "Pleiades VII": 2.55,
    "Orion Nebula I": 2.75,
    "Cygnus Loop IV": 2.95,
    "Crab Pulsar Base": 3.15,
    "Andromeda X": 3.35,
    "Triangulum V": 3.55,
    "Whirlpool III": 3.75,
    "Sombrero Base": 3.95,

    # === ORIGINAL PLANETS (The Extra Stupid Hundred) ===
    "Astraeus Prime": 0.85,
    "Kylo-Mina": 1.45,
    "Terra-Silica": 1.12,
    "Xeno-Hearth": 0.68,
    "Borealis III": 1.75,
    "Crimson Zenith": 0.92,
    "Veridian Reach": 1.55,
    "Onyx Prime V": 2.05,
    "Stygian Veil I": 3.2,
    "Aetheria Minor": 0.55,
    "Lumara Bright": 1.33,
    "Draksus Deep": 1.7,
    "Cinderfall Base": 2.15,
    "Miranus Port": 0.9,
    "Kryll Nexus": 0.8,
    "Veldt Wilds": 1.65,
    "Zephyr Winds": 0.77,
    "Rylos Prime": 1.5,
    "Aerthos VI": 1.1,
    "Pyreos Core": 2.3,
    "Aquata Major": 0.6,
    "Chronos Station": 0.5,
    "Glimmer Dust": 1.9,
    "Ironclad Forge": 2.2,
    "Shade Coast": 1.3,
    "Luminus A": 0.7,
    "Ebon Reach II": 1.8,
    "Sunstone Reef": 0.9,
    "Fogbank Station": 1.4,
    "Aurus Gold": 1.2,
    "Solis Dawn": 0.75,
    "Grimoire VII": 1.6,
    "Tundra-4": 1.85,
    "Oasis-Beta II": 0.95,
    "Ironclad-Delta": 2.1,
    "Arcadia Gate": 0.88,
    "Whisper Echo": 1.22,
    "Echo VII": 1.5,
    "Sentinel Outpost": 1.1,
    "Apex Seven-Alpha": 0.8,
    "Tarkus VI": 1.7,
    "Orionis Port": 1.9,
    "Phobos Station 3": 1.0,
    "Hesperus Prime": 1.3,
    "Prometheus IX-C": 1.5,
    "Astrakhan": 1.7,
    "Galactica Core": 1.9,
    "Cygnus Ring": 2.1,
    "Pegasus Delta": 2.3,
    "Lyra Station": 2.5,
    "Phoenix Point": 2.7,
    "Draco System": 2.9,
    "Hydra Prime": 3.1,
    "Orion Spur X": 3.3,
    "Canis Minor": 3.5,
    "Serpentis Base": 3.7,
    "Gemini Nexus": 3.9,
    "Vela Sector": 4.1,
    "Crux Colony": 4.3,
    "Carina Deep": 4.5,
    "Puppis Star": 4.7,
    "Pavo Dust": 4.9,
    "Volans Rift": 0.15,
    "Mensa Peak": 0.25,
    "Dorado Gate": 0.35,
    "Octans Ice": 0.45,
    "Caelum Forge": 0.55,
    "Fornax Base": 0.65,
    "Reticulum": 0.75,
    "Horologium": 0.85,
    "Pictor Flats": 0.95,
    "Sculptor Void": 1.05,
    "Antlia Grid": 1.15,
    "Circinus Loop": 1.25,
    "Indus Station": 1.35,
    "Microscopium": 1.45,
    "Norma Cluster": 1.55,
    "Telescopium": 1.65,
    "Triangulum Australe": 1.75,
    "Corona Australis": 1.85,
    "Scutum Starfield": 1.95,
    "Centaurus Arm": 2.05,
    "Andromeda Xenos": 2.15,
    "Pinwheel Minor": 2.25,
    "Bode's Outpost": 2.35,
    "Cigar System": 2.45,
    "Black Eye Station": 2.55,
    "Tadpole Nebula": 2.65,
    "Veil Gamma": 2.75,
    "Ring Nebula Base": 2.85,
    "Helix Prime": 2.95,
    "Owl Sector": 3.05
}